__title__ = "kite_trade"
__description__ = "The official Python client for the Kite Connect trading API"
__url__ = "https://kite.trade"
__download_url__ = "https://github.com/Manishankar152207/kite_trade.git"
__version__ = "0.0.1"
__author__ = "Manishankar"
__author_email__ = "csmanishankar@gmail.com"
__license__ = "MIT"